"""add per-group daily translation limit

Revision ID: e1f45b428185
Revises: 55329667c6de
Create Date: 2026-08-23 09:05:14.818910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f45b428185'
down_revision: Union[str, None] = '55329667c6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_daily_counters',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('translated_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'date')
    )
    op.add_column('groups', sa.Column('daily_message_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'daily_message_limit')
    op.drop_table('group_daily_counters')
    # ### end Alembic commands ###
